name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '59 23 28-31 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        crate_name:
          - icx-asset
          - icx-cert
          - icx-proxy

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: pre-install
      run: |
          sudo apt-get update
          sudo apt-get install -y build-essential musl-tools
          rustup target add x86_64-unknown-linux-musl
          
    - name: Install Dependencies
      run: |
        cargo install ${{matrix.crate_name}} --target x86_64-unknown-linux-musl
    
    - name: Strip Debug Symbols
      run: strip ~/.cargo/bin/${{ env.BINARY_NAME }}

    - name: Copy files
      run: |
        mkdir -p combined_artifacts
        cp -rfv ~/.cargo/bin/${{matrix.crate_name}} combined_artifacts/
  
  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
  
    steps:

    - name: Get Timestamp
      id: timestamp
      run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      
    - name: Upload Combined Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rust-artifacts-${{ env.TIMESTAMP }}
        path: combined_artifacts/*

    - name: Upload crates to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: combined_artifacts/*
        asset_name: combined_release_${{ env.TIMESTAMP }}
        tag: ${{ github.ref }}
        overwrite: true

