name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '59 23 28-31 * *'  # Runs at 11:00 PM UTC on the 28th, 29th, 30th, and 31st day of each month

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        crate_name:
          - icx-asset
          - icx-cert
          - icx-proxy

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get Timestamp
      id: timestamp
      run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      
    - name: Install Dependencies
      run: cargo install ${{ matrix.crate_name }}
      
    - name: Create Artifact
      uses: actions/upload-artifact@v3
      #with: # Alternative 1
      #name: rust-artifacts
      #  path: |
      #    ~/.cargo/bin/crate_1
      #    ~/.cargo/bin/crate_2
      with: # Alternative 2
        name: ${{ matrix.crate_name }}
        path: |
          ~/.cargo/bin/${{ matrix.crate_name }} 
      #with: # Alternative 3
      #  name: rust-artifacts
      #  path: ~/.cargo/bin

    - name: Set up Git
      run: |
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name "${GITHUB_ACTOR}"
      
    # Add a condition to only execute the following steps for the last matrix job
    - name: Build and Push Combined Tag
      run: |
          mkdir -p combined_artifacts
          cp -r ~/.cargo/bin/icx-asset combined_artifacts/
          cp -r ~/.cargo/bin/icx-cert combined_artifacts/
          cp -r ~/.cargo/bin/icx-proxy combined_artifacts/
          git add combined_artifacts
          git commit -m "Add combined artifacts"
          git tag -a combined_release_${{ env.TIMESTAMP }} -m "Combined release ${GITHUB_SHA}"
          git push origin combined_release_${{ env.TIMESTAMP }}
      if: github.event_name == 'push'

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "combined_artifacts"
        tag: combined_release_${{ env.TIMESTAMP }}
        name: Combined Release
      if: github.event_name == 'push'
