name: Multi-Crate Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '59 23 28-31 * *'  # Runs at 11:00 PM UTC on the 28th, 29th, 30th, and 31st day of each month
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        crate_name:
          - just

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Rust
      uses: moonrepo/setup-rust@v1
      with:
        channel: stable
        profile: minimal
        cache-base: main
    
    - name: Use orhun/git-cliff-action
      uses: orhun/git-cliff-action@v2

    - name: Generate Release Notes
      run: git-cliff

    - name: Set up Git
      run: |
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name "${GITHUB_ACTOR}"
        
    - name: Create and Push Tag
      run: git tag -a crate-${{ matrix.crate_name }} -m "Release crate-${{ matrix.crate_name }}"
      if: github.event_name == 'push'

    - name: Push Tag
      run: git push origin crate-${{ matrix.crate_name }}
      if: github.event_name == 'push'

    - name: Release
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "~/.cargo/bin/*"
        bodyFile: "RELEASE_NOTES.md"
