name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '59 23 28-31 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        crate_name:
          #- icx-asset
          - icx-cert
          #- icx-proxy

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get Timestamp
      id: timestamp
      run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      
    - name: pre-install
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential musl-tools
        CRATE_VERSION=$(cargo install --list | grep "${{ matrix.crate_name }}" | cut -d ' ' -f 1)
        echo ${{CRATE_VERSION}}
        rustup target add x86_64-unknown-linux-musl

    - name: Install Dependencies
      run: |
        cargo install ${{ matrix.crate_name }} --target x86_64-unknown-linux-musl
        echo "CRATE_VERSION=${CRATE_VERSION}" >> $GITHUB_ENV
    
    - name: Strip Debug Symbols
      run: strip ~/.cargo/bin/${{matrix.crate_name}}

    - name: Copy files
      run: |
        mkdir -p combined_artifacts
        cp -rfv ~/.cargo/bin/${{matrix.crate_name}} combined_artifacts/${{matrix.crate_name}}_${{ env.CRATE_VERSION }}

    - name: Upload Combined Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: 'Combined Airtifacts'
        path: ./combined_artifacts/${{ matrix.crate_name }}_${{ env.CRATE_VERSION }}
